version: "3"

services:
  db:
    env_file: .env
    network_mode: "bridge"

  runestone:
    ports:
      - "80"
    network_mode: "bridge"
    env_file: .env
    environment:
      WEB2PY_CONFIG: "production"
      WEB2PY_ADMIN_SECURITY_BYPASS: "false"
      RUNESTONE_USE_SERVICES: "true"
      RUNESTONE_USE_HTTPS: "true"
      VIRTUAL_HOST: "${RUNESTONE_HOST}"
      LETSENCRYPT_HOST: "${RUNESTONE_HOST}"
      LETSENCRYPT_EMAIL: "${ADMIN_EMAIL}"
      PGOPTIONS: "-c 'custom.web2py_private_key=${WEB2PY_PRIVATE_KEY}'"
      WEB2PY_PASSWORD: "${WEB2PY_PASSWORD}"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    network_mode: "bridge"
    links:
      - db
    ports:
      - "80"
    depends_on:
      - "db"
    env_file: .env
    environment:
      PGADMIN_LISTEN_PORT: "80"
      PGADMIN_DEFAULT_EMAIL: "${ADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD}"
      VIRTUAL_HOST: "db.${RUNESTONE_HOST}"
      LETSENCRYPT_HOST: "db.${RUNESTONE_HOST}"
      LETSENCRYPT_EMAIL: "${ADMIN_EMAIL}"
    volumes:
      - ./pgadmin/servers.json:/servers.json

  redis:
    network_mode: "bridge"

  dashboard:
    image: "nginx:latest"
    restart: always
    network_mode: "bridge"
    ports:
      - "80"
    env_file: .env
    environment:
      VIRTUAL_HOST: "dashboard.${RUNESTONE_HOST}"
      LETSENCRYPT_HOST: "dashboard.${RUNESTONE_HOST}"
      LETSENCRYPT_EMAIL: "${ADMIN_EMAIL}"
    volumes:
      - ./dashboard/dist/spa:/usr/share/nginx/html

  hasura:
    ports:
      - "8080"
    network_mode: "bridge"
    env_file: .env
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://runestone:${POSTGRES_PASSWORD}@db/runestone"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_ADMIN_SECRET_KEY}"
      HASURA_GRAPHQL_JWT_SECRET: "${HASURA_GRAPHQL_JWT_SECRET}"
      VIRTUAL_HOST: "api.${RUNESTONE_HOST}"
      LETSENCRYPT_HOST: "api.${RUNESTONE_HOST}"
      LETSENCRYPT_EMAIL: "cedonner@gmail.com"
    

  hasura-backend-plus:
    image: nhost/hasura-backend-plus:latest
    ports:
      - '3000'
    environment:
      SERVER_URL: "https://hbp.${RUNESTONE_HOST}"
      HASURA_ENDPOINT: http://hasura:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_ADMIN_SECRET_KEY}'
      JWT_ALGORITHM: HS512
      VIRTUAL_HOST: "hbp.${RUNESTONE_HOST}"
      LETSENCRYPT_HOST: "hbp.${RUNESTONE_HOST}"
      LETSENCRYPT_EMAIL: "cedonner@gmail.com"
