version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"

  redis:
    image: redis

  runestone:
    image: donnerc/runestone-server:1920
    restart: always
    #command: tail -F peanutbutter
    volumes:
      - ./:/srv/web2py/applications/runestone
    links:
      - db
      - redis
    depends_on:
      - "db"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      WEB2PY_CONFIG: "production"
      WEB2PY_MIGRATE: "Yes"
      DBURL: "postgresql://runestone:${POSTGRES_PASSWORD}@db/runestone"
      DEV_DBURL: "postgresql://runestone:${POSTGRES_PASSWORD}@db/runestone"
      TEST_DBURL: "postgresql://runestone:${POSTGRES_PASSWORD}@db/runestone_test"
      RUNESTONE_HOST: "${RUNESTONE_HOST}"
      WEB2PY_PASSWORD: "${WEB2PY_PASSWORD}"
      WEB2PY_ADMIN_SECURITY_BYPASS: "true"
      RUNESTONE_USE_SERVICES: "true"
      RUNESTONE_USE_HTTPS: "false"
      RUNESTONE_DISABLE_REGISTER: "true"
      RUNESTONE_USE_DYNAMIC_PAGES: "true"
      RUNESTONE_BUILD_BOOKS_ON_STARTUP: "false"
      REDIS_URI: "redis://redis:6379/0"
