services:
  db:
    depends_on:
    - db
    environment:
      PGADMIN_PASSWORD: maison
      POSTGRES_DB: runestone
      POSTGRES_PASSWORD: runestone
      POSTGRES_USER: runestone
    image: postgres
    network_mode: bridge
  hasura:
    environment:
      HASURA_ADMIN_SECRET_KEY: biduletruc
      HASURA_GRAPHQL_ADMIN_SECRET: biduletruc
      HASURA_GRAPHQL_DATABASE_URL: postgres://runestone:runestone@db/runestone
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_JWT_SECRET: '''{"type": "HS512","key": "WnpAGcjSNKJXaKaGUhmnJLmweCllXKtqTCZrreRwnmHTsJIEHMUhYYRgcMuBVmCN","claims_namespace":
        "https://21-learning.com/jwt/claims","claims_format": "json","issuer": "21-learning.com"}'''
    image: hasura/graphql-engine:v1.1.0
    links:
    - db
    network_mode: bridge
    ports:
    - 8080/tcp
    restart: always
  pgadmin:
    depends_on:
    - db
    environment:
      PGADMIN_DEFAULT_EMAIL: cedonner@gmail.com
      PGADMIN_DEFAULT_PASSWORD: maison
      PGADMIN_LISTEN_PORT: '80'
      PGADMIN_PASSWORD: maison
    image: dpage/pgadmin4:latest
    links:
    - db
    network_mode: bridge
    ports:
    - 80/tcp
    - 9000:9000/tcp
    restart: always
    #volumes:
    #- /root/runestone-server/pgadmin/servers.json:/servers.json:rw
  redis:
    image: redis
    network_mode: bridge
  runestone:
    depends_on:
    - db
    environment:
      DBURL: postgresql://runestone:runestone@db/runestone
      DEV_DBURL: postgresql://runestone:runestone@db/runestone
      PGOPTIONS: -c 'custom.web2py_private_key=sha512:16492eda-ba33-48d4-8748-98d9bbdf8d33RUNESTONE_REMOTE=true'
      POSTGRES_DB: runestone
      POSTGRES_PASSWORD: runestone
      POSTGRES_USER: runestone
      REDIS_URI: redis://redis:6379/0
      RUNESTONE_BUILD_BOOKS_ON_STARTUP: "false"
      RUNESTONE_DISABLE_REGISTER: "true"
      RUNESTONE_HOST: courses.21-learning.com
      RUNESTONE_USE_DYNAMIC_PAGES: "true"
      RUNESTONE_USE_HTTPS: "true"
      RUNESTONE_USE_SERVICES: "true"
      TEST_DBURL: postgresql://runestone:runestone@db/runestone_test
      WEB2PY_ADMIN_SECURITY_BYPASS: "false"
      WEB2PY_CONFIG: production
      WEB2PY_MIGRATE: "Yes"
      WEB2PY_PASSWORD: maison
      WEB2PY_PRIVATE_KEY: sha512:16492eda-ba33-48d4-8748-98d9bbdf8d33RUNESTONE_REMOTE=true
    image: runestone/server
    links:
    - db
    - redis
    network_mode: bridge
    ports:
    - 80/tcp
    restart: always
    volumes:
    - /root/runestone-server:/srv/web2py/applications/runestone:rw
